site_name: PageBot
repo_url: https://github.com/typenetwork/PageBot/
repo_name: PageBot
theme: readthedocs
pages:
  - 'Home': 'index.md'
  - 'How To': 'howto.md'
  - 'About': 'about.md'
  - 'pagebot API': 'pagebot/index.md'
  - 'pagebot.builders':
     - 'pagebot.builders': 'pagebot/builders/index.md'
     - 'pagebot.builders.basebuilder': 'pagebot/builders/basebuilder.md'
        
