site_name: PageBot
repo_url: https://github.com/typenetwork/PageBot/
repo_name: PageBot
docs_dir: Doc
theme: readthedocs
pages:
 - 'Home': 'index.md'
 - 'How To': 'howto.md'
 - 'About': 'about.md'
 - 'pagebot':
    - 'pagebot/index.md'
    - 'pagebot/composer.md'
    - 'pagebot/document.md'
    - 'pagebot/style.md'
    - 'pagebot/typesetter.md'
 - 'pagebot/md':
    - 'pagebot/md/index.md'
    - 'pagebot/md/footnotes.md'
    - 'pagebot/md/literature.md'
 - 'pagebot/elements':
    - 'pagebot/elements/index.md'
    - 'pagebot/elements/element.md'
    - 'pagebot/elements/pbgalley.md'
    - 'pagebot/elements/pbimage.md'
    - 'pagebot/elements/pbline.md'
    - 'pagebot/elements/pboval.md'
    - 'pagebot/elements/pbpage.md'
    - 'pagebot/elements/pbpolygon.md'
    - 'pagebot/elements/pbrect.md'
    - 'pagebot/elements/pbruler.md'
    - 'pagebot/elements/pbtable.md'
    - 'pagebot/elements/pbtext.md'
    - 'pagebot/elements/pbtextbox.md'
 - 'pagebot/elements/paths':
    - 'pagebot/elements/paths/index.md'
    - 'pagebot/elements/paths/glyphpath.md'
    - 'pagebot/elements/paths/pbpath.md'
 - 'pagebot/elements/variablefonts':
    - 'pagebot/elements/variablefonts/index.md'
    - 'pagebot/elements/variablefonts/variablecircle.md'
    - 'pagebot/elements/variablefonts/variablecube.md'
    - 'pagebot/elements/variablefonts/variablecube2.md'
    - 'pagebot/elements/variablefonts/variableeditor.md'
    - 'pagebot/elements/variablefonts/variableglyphs.md'
    - 'pagebot/elements/variablefonts/variablescatter.md'
 - 'pagebot/elements/views':
    - 'pagebot/elements/views/index.md'
    - 'pagebot/elements/views/defaultview.md'
    - 'pagebot/elements/views/htmlcssview.md'
    - 'pagebot/elements/views/kirbyview.md'
    - 'pagebot/elements/views/singleview.md'
    - 'pagebot/elements/views/thumbview.md'
    - 'pagebot/elements/views/view.md'
 - 'pagebot/builders':
    - 'pagebot/builders/index.md'
    - 'pagebot/builders/basebuilder.md'
    - 'pagebot/builders/mdblogbuilder.md'
 - 'pagebot/builders/kirby':
    - 'pagebot/builders/kirby/index.md'
    - 'pagebot/builders/kirby/kirbybuilder.md'
 - 'pagebot/builders/htmlcss':
    - 'pagebot/builders/htmlcss/index.md'
    - 'pagebot/builders/htmlcss/basehtmlcssbuilder.md'
    - 'pagebot/builders/htmlcss/gridbuilder.md'
    - 'pagebot/builders/htmlcss/simplebuilder.md'
    - 'pagebot/builders/htmlcss/simplehtmlcssbuilder.md'
 - 'pagebot/contributions':
    - 'pagebot/contributions/index.md'
 - 'pagebot/contributions/adobe':
    - 'pagebot/contributions/adobe/index.md'
 - 'pagebot/contributions/adobe/kerndump':
    - 'pagebot/contributions/adobe/kerndump/index.md'
    - 'pagebot/contributions/adobe/kerndump/dumpKerningFeatureFromOTF.md'
    - 'pagebot/contributions/adobe/kerndump/getKerningPairsFromOTF.md'
 - 'pagebot/contributions/filibuster':
    - 'pagebot/contributions/filibuster/index.md'
    - 'pagebot/contributions/filibuster/blurb.md'
    - 'pagebot/contributions/filibuster/blurbwriter.md'
    - 'pagebot/contributions/filibuster/test.md'
    - 'pagebot/contributions/filibuster/titlecase.md'
 - 'pagebot/contributions/filibuster/content':
    - 'pagebot/contributions/filibuster/content/index.md'
    - 'pagebot/contributions/filibuster/content/aerospace.md'
    - 'pagebot/contributions/filibuster/content/articles.md'
    - 'pagebot/contributions/filibuster/content/auction.md'
    - 'pagebot/contributions/filibuster/content/automotive.md'
    - 'pagebot/contributions/filibuster/content/book_reference.md'
    - 'pagebot/contributions/filibuster/content/boymechanic.md'
    - 'pagebot/contributions/filibuster/content/classified.md'
    - 'pagebot/contributions/filibuster/content/commercial.md'
    - 'pagebot/contributions/filibuster/content/corporate.md'
    - 'pagebot/contributions/filibuster/content/creditcard.md'
    - 'pagebot/contributions/filibuster/content/design.md'
    - 'pagebot/contributions/filibuster/content/designarticle.md'
    - 'pagebot/contributions/filibuster/content/entertainment.md'
    - 'pagebot/contributions/filibuster/content/event.md'
    - 'pagebot/contributions/filibuster/content/filenames.md'
    - 'pagebot/contributions/filibuster/content/filibuster.md'
    - 'pagebot/contributions/filibuster/content/financial.md'
    - 'pagebot/contributions/filibuster/content/general.md'
    - 'pagebot/contributions/filibuster/content/geography.md'
    - 'pagebot/contributions/filibuster/content/horoscope.md'
    - 'pagebot/contributions/filibuster/content/internet.md'
    - 'pagebot/contributions/filibuster/content/jargon.md'
    - 'pagebot/contributions/filibuster/content/journalism.md'
    - 'pagebot/contributions/filibuster/content/legal.md'
    - 'pagebot/contributions/filibuster/content/letterror.md'
    - 'pagebot/contributions/filibuster/content/literature.md'
    - 'pagebot/contributions/filibuster/content/living.md'
    - 'pagebot/contributions/filibuster/content/medical.md'
    - 'pagebot/contributions/filibuster/content/modernmedia.md'
    - 'pagebot/contributions/filibuster/content/music.md'
    - 'pagebot/contributions/filibuster/content/names.md'
    - 'pagebot/contributions/filibuster/content/navigation.md'
    - 'pagebot/contributions/filibuster/content/news.md'
    - 'pagebot/contributions/filibuster/content/politics.md'
    - 'pagebot/contributions/filibuster/content/portal.md'
    - 'pagebot/contributions/filibuster/content/quotations.md'
    - 'pagebot/contributions/filibuster/content/realestate.md'
    - 'pagebot/contributions/filibuster/content/reviews.md'
    - 'pagebot/contributions/filibuster/content/sciences.md'
    - 'pagebot/contributions/filibuster/content/sports.md'
    - 'pagebot/contributions/filibuster/content/staff.md'
    - 'pagebot/contributions/filibuster/content/superheroes.md'
    - 'pagebot/contributions/filibuster/content/twitter.md'
 - 'pagebot/interaction':
    - 'pagebot/interaction/index.md'
    - 'pagebot/interaction/variables.md'
 - 'pagebot/publications':
    - 'pagebot/publications/index.md'
    - 'pagebot/publications/pagebotdoc.md'
    - 'pagebot/publications/poster.md'
    - 'pagebot/publications/publication.md'
    - 'pagebot/publications/singlepage.md'
    - 'pagebot/publications/typespecimen.md'
 - 'pagebot/toolbox':
    - 'pagebot/toolbox/index.md'
    - 'pagebot/toolbox/dating.md'
    - 'pagebot/toolbox/drawparts.md'
    - 'pagebot/toolbox/markers.md'
    - 'pagebot/toolbox/mathematics.md'
    - 'pagebot/toolbox/timemark.md'
    - 'pagebot/toolbox/transform3d.md'
    - 'pagebot/toolbox/transformer.md'
 - 'pagebot/fonttoolbox':
    - 'pagebot/fonttoolbox/index.md'
    - 'pagebot/fonttoolbox/designspacemodel.md'
    - 'pagebot/fonttoolbox/otlTools.md'
    - 'pagebot/fonttoolbox/svg2drawbot.md'
    - 'pagebot/fonttoolbox/ttftools.md'
    - 'pagebot/fonttoolbox/varfontdesignspace.md'
    - 'pagebot/fonttoolbox/variablefontbuilder.md'
 - 'pagebot/fonttoolbox/analyzers':
    - 'pagebot/fonttoolbox/analyzers/index.md'
    - 'pagebot/fonttoolbox/analyzers/contour.md'
    - 'pagebot/fonttoolbox/analyzers/glyphanalyzer-TNBITS.md'
    - 'pagebot/fonttoolbox/analyzers/glyphanalyzer.md'
    - 'pagebot/fonttoolbox/analyzers/point.md'
    - 'pagebot/fonttoolbox/analyzers/pointcontext.md'
    - 'pagebot/fonttoolbox/analyzers/pointcontextlist.md'
    - 'pagebot/fonttoolbox/analyzers/segment.md'
 - 'pagebot/fonttoolbox/objects':
    - 'pagebot/fonttoolbox/objects/index.md'
    - 'pagebot/fonttoolbox/objects/family.md'
    - 'pagebot/fonttoolbox/objects/font.md'
    - 'pagebot/fonttoolbox/objects/fontinfo.md'
    - 'pagebot/fonttoolbox/objects/glyph.md'
 - 'pagebot/fonttoolbox/unicodes':
    - 'pagebot/fonttoolbox/unicodes/index.md'
    - 'pagebot/fonttoolbox/unicodes/unicoderanges.md'
    - 'pagebot/fonttoolbox/unicodes/unicoderangesdata.md'
 - 'pagebot/conditions':
    - 'pagebot/conditions/index.md'
    - 'pagebot/conditions/align.md'
    - 'pagebot/conditions/condition.md'
    - 'pagebot/conditions/floating.md'
    - 'pagebot/conditions/flow.md'
    - 'pagebot/conditions/score.md'
