# -*- coding: UTF-8 -*-

"""
        living
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
"""

__version__ = '4.0'


content = {
    'boymechanic_ankeiler': ['Having fun <#,odd_action#> while <#odd_action#>.'],
    'odd_action': [
        '<#odd_verbs_gerund#> <#article,odd_descriptor#> <#odd_noun#>',
        '<#odd_verbs_gerund#> <#article,odd_noun#> with some <#odd_material#>',
        '<#odd_verbs_gerund#> <#article,odd_noun#> with <#article,odd_noun#> and some <#odd_material#>',
        '<#odd_verbs_gerund#> <#article,odd_noun#> without <#odd_moreverbs_gerund#> it',
    ],
    'odd_adj': [
        'embossed',
        'atmospheric',
        'electric',
        'broken',
        'photovoltaic',
        'stained',
        'tarnished',
    ],
    'odd_descriptor': [
        'homemade',
        'homemade',
        'homemade',
        'homemade',
        'homemade',
        'digital',
        'live',
        'dead',
        '<#odd_adj#>',
    ],
    'odd_material': [
        'glass',
        'wood',
        'flatiron',
        'felt',
        'tin',
        'wool',
        'cotton',
        'leather',
        'string',
    ],
    'odd_moreverbs_gerund': [
        'relieving ',
        'inflating ',
        'closing',
        'baking',
        'reducing',
        'advertising',
        'fish scaling',
        'mixing',
        'preventing',
    ],
    'odd_noun': [
        'acid',
        'siphon',
        'alarm',
        'record box',
        'combination lathe',
        'applications',
        'toy balloon',
        'air pressure',
        'sleepwalker',
        'fuse wire',
        'guide',
        'principle',
        'idea',
        'model boat',
        'amperage',
        'hammer',
        'small wound',
        'bread',
        'ball-clasp purse',
        'broom',
        'camera',
        'radio',
        'box',
        'container',
        'bottle',
        'sulphuric acid',
        'itch',
        'limb',
        'calcium deposit',
        'stain',
        'brush',
        'splinter',
        'organ',
    ],
    'odd_thing': [
        '<#odd_descriptor#> <#odd_noun#> for <#article,odd_adj#> <#odd_noun#>',
        '<#odd_verbs_gerund#> <#odd_noun#> for <#odd_descriptor#> <#odd_noun#>',
        '<#odd_verbs_gerund#> <#odd_noun#> with <#odd_descriptor#> <#odd_noun#>',
        '<#odd_verbs_gerund#> <#odd_noun#> with <#article,odd_descriptor#> <#odd_noun#>',
        '<#article, odd_adj#> <#odd_noun#>, <#odd_verbs_gerund#>',
    ],
    'odd_topics': [
        'ways to keep home accounts',
        'acid siphon',
        'how to make advertising lantern slides',
        'model boat with aerial propeller',
        'aeroplane kite',
        'air pencil to make embossed letters',
        'relieving air pressure when closing record boxes',
        'alarm for sleepwalker',
        u'amateur mechanic’s combination lathe',
        'reducing amperage of fuse wire',
        'applications for small wounds',
        'atmospheric thermo engine',
        'baking bread in hot sand',
        'repairing a broken ball-clasp purse',
        'inflating toy balloons',
        'electric-light bulb as barometer',
        'removing basketball from closed-bottom receptacle',
        'preserving dry batteries',
        'bearings for model work',
        'how to make a continuously ringing bell',
        'adjustable bench stop',
        'mechanical bicycle horn',
        'lantern slide binding machine',
        'removing black deposits on bathtubs',
        'ruling blank books',
        'automatic blowpipe',
        'boats-an oar holder',
        'bobsled, inexpensive',
        'boiling cracked eggs',
        'ear repair on bucket',
        'Mile-O-View camera',
        'camp stoves',
        'ro repair leak in canoe',
        'one-piece casting rod',
        'cherry-pitter',
        'electric chime clock',
        'how to clean jewelry',
        'electric chime clock',
        'reading date of worn coin',
        'callar fasteners',
        'comb cleaner',
        'cooking food in paper',
        'removing cork from bottle',
        'how to make a costumer',
        'cover for bottle',
        'croquet playing at night',
        'homemade dibble',
        'exerciser for chained dog',
        'dowel turning tool',
        'paper drinking cup',
        'homemade electric bed warmer',
        'electric flatiron',
        'electric light mystery',
        'electric time light',
        'electrical apparatus',
        'electrically operated doorknob',
        'how to make falling blocks',
        'mending break in felt',
        'laborotry force filter',
        'attractor for fish. game',
        'electric fishing signal',
        'homemade floor polisher',
        'frosting glass',
        'fountain pen, homemade',
        'furniture- jarndiniere pedestal',
        u'D’Arsonval galvanometer',
        'game played on ice',
        'centering gauge',
        'grape arbor built of poles',
        'kraut and root grinder',
        'polishing gunstocks',
    ],
    'odd_verb': [
        'repair',
        'fix',
        'open',
        'close',
        'clean',
        'use',
        'make',
        'inflate',
        'bake',
    ],
    'odd_verbs_gerund': [
        'repairing',
        'fixing',
        'removing',
        'cleaning',
        'using',
        'making',
        '<#odd_moreverbs_gerund#>',
    ],
    }

