# -*- coding: UTF-8 -*-

"""
        literature
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
"""

__version__ = '4.0'


content = {
    'book_headline': [
        '<#book_pseudoscience_author#>','<#book_pseudoscience_title#>','<#book_pseudoscientific#>',
        '<#book_title_front#>',
    ],
    'book_section':    ['Books', 'Books', 'Books', 'Books', 'Books', 'Books',
        'Books', 'Books', 'Books', 'Books', 'Books', 'Books',
        'New books', 'Literature', 'Authors', 'E-books', 'E-books', 'E-books', 'Published',
        'New published','My library','Publishing','From the library',
    ],
    'book_ankeiler':['<#^,book_phylosophy_title#>',
        ],
    'book_pseudosci_adj': [
        'eternal ',
        'golden ',
        'inspiring ',
        'inspired ',
        'negative ',
        'positive ',
        'divine ',
        'universal ',
        'liberal ',
        'spirited ',
        'early ',
        'late ',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
    ],
    'book_pseudoscience_author': [
        '<#sci_titles_px#> <#names_last_absurdlyBritish#>, <#sci_titles_sx#>',
        '<#names_last_absurdlyBritish#>, <#university_dept#>',
        '<#name#>',
        '<#name#>, <#sci_titles_px#> at <#university_dept#>',
    ],
    'book_pseudoscience_title': [
        '"<#book_pseudoscientific#>" by <#book_pseudoscience_author#>',
        '"<#book_pseudoscientific#>, <#num_roman#>" by <#book_pseudoscience_author#>',
    ],
    'book_pseudoscientific': [
        '<#^,lit_figures#> and <#^,lit_figures#>',
        '<#^,lit_figures#> as seen by <#book_pseudosci_adj#><#sci_pseudo#>',
        '<#^,sci_pseudo#>, <#^,lit_figures#> and <#^,lit_figures#>',
        '<#^,lit_figures#> and <#sci_disciplines#>',
        '<#^,lit_figures#> in the history of <#sci_disciplines#>',
        '<#^,book_pseudosci_adj#><#sci_pseudo#> and <#sci_disciplines#>',
        '<#^,book_pseudosci_adj#><#sci_pseudo#> as <#sci_disciplines#>',
        'The role of <#sci_disciplines#> in <#sci_pseudo#>',
        'The influence of <#book_pseudosci_adj#><#sci_pseudo#> on <#sci_disciplines#>',
        '<#^,book_pseudosci_adj#><#sci_pseudo#> and <#^,lit_figures#>',
        'The role of <#sci_pseudo#> in <#sci_pseudo#>',
        '<#^,sci_pseudo#> and <#sci_pseudo#> <#book_pseudoscientific_sx#>',
        '<#book_pseudoscientific#>',
    ],
    'book_pseudoscientific_sx': [
        '(<-randint(1700, 1800)->-<-randint(1801, 1900)->)',
    ],
    'book_title': [
        '"<#state_of_mind#> and <#state_of_mind#>" by Jane Austen',
    ],
    'lit_figures': [
        'goya',
        'rembrandt',
        'elgreco',
        'turner',
        'constable',
        'vangogh',
        'renoir',
        'seurat',
        'rubens',
        'klimt',
        'monet',
        'lautrec',
        'matisse',
        'mondrian',
        'ruscha',
        'reinhardt',
        'malevich',
        'dali',
        'magritte',
        'ensor',
        'bach',
        'handel',
        'brahms',
        'beethoven',
        'bartok',
        'chopin',
        'delibes',
        'debussy',
        'mahler',
        'copland',
        'marais',
        'forqueray',
        'lully',
        'couperin',
        'grieg',
        'wagner',
        'tarantino',
        'truffaut',
        'vansant',
        'lumiere',
        'spielberg',
        'cronenberg',
        'lucas',
        'bunuel',
        'bergman',
        'bronte',
        'austen',
        'kafka',
        'chekov',
        'beckett',
        'camus',
        'turgenev',
        'james',
        'hemingway',
        'fitzgerald',
        'wright',
        'ellison',
        'fourier',
        'euler',
        'mandelbrot',
        'copernicus',
        'galileo',
        'einstein',
        'tesla',
        'whitney',
        'edison',
        'planck',
        'leonardo',
        'pythagoras',
        'bohr',
        'newton',
        'archimedes',
        'coulomb',
        'fahrenheit',
        'faraday',
        'fermi',
        'feynman',
        'hawking',
        'geiger',
        'curie',
        'kelvin',
        'ohm',
        'penzias',
        'roentgen',
        'volta',
    ],
    'lit_mythology': [
        'zeus',
        'apollo',
        'hermes',
        'athena',
        'achilles',
        'antigone',
        'aphrodite',
        'anubis',
        'arachne',
        'asgard',
        'atlantis',
        'atlas',
        'aurora',
        'cadmus',
        'calliope',
        'calypso',
        'centaur',
        'charon',
        'charybdis',
        'cronus',
        'cupid',
        'cyclops',
        'daedalus',
        'daphne',
        'demeter',
        'diana',
        'dido',
        'electra',
        'erato',
        'europa',
        'euridyce',
        'euterpe',
        'flora',
        'ganymede',
        'gorgon',
        'hades',
        'hector',
        'hera',
        'heracles',
        'hermes',
        'hyperion',
        'icarus',
        'janus',
        'jocasta',
        'leda',
        'lucian',
        'medea',
        'minerva',
        'narcissus',
        'nestor',
        'odin',
        'odysseus',
        'oedipus',
        'orcus',
        'osiris',
        'paris',
        'perseus',
        'phaedra',
        'poseidon',
        'proteus',
        'psyche',
        'pyramus',
        'satyr',
        'scylla',
        'sisyphus',
        'sphinx',
        'styx',
        'tantalus',
        'tereus',
        'thalia',
        'thor',
        'thoth',
        'titan',
        'triton',
        'ulysses',
        'urania',
        'vulcan',
    ],
    'state_of_mind': [
        'Pride',
        'Prejudice',
        'Stubborness',
        'Anger',
        'Fury',
        'Depression',
        'Mild Amusement',
        'Consolation',
    ],
}

