# -*- coding: UTF-8 -*-

"""
        living
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
"""

__version__ = '4.0'


content = {
    'portal_anyshortname': [
        'Cars','Games','Health','Home','Society','Sports','Busy',
        'Parts','Service','Garage','Art','Internet','News','Regional',
        'Science','Society','Jobs','Suits','Movies','TV','Music',
        'Stars','Basic','Soccer','Football','Tennis','Jogger','Kids',
        'Chats','Mail','Babies','Dance','Education','Camping','Boats',
        'Draw','Math','Finance','Bank','Office','Dinner','Meetings',
        'Tetris','Travel','Jazz','Soul','Housing','Pizza','Asia','Europe',
        'Medical','Careers','Food','Holiday','Family','School','Voting',
        'Educate','Events','Relics','Friends','Phone','Stock','Bones',
        'Skeleton','Fair','Trade','Commerce','Show','Paris','Boston',
        'Faces','Twitter','Trees','Xierpa','Login','Mice','Phone','Delft',
        'iPad','iPhone','Android','Med','Facebook','Chickens','Business',
        'Hobby','Computer','Gaming','Design','Hike','Things','Hiking',
        'Garden','Pets','Chicks','Biking','Diet','Fish','Shops','Fonts',
        'X-Box','Jokes','Wash','Beach','Soccer','Market','Places',
    ],
    'portal_anyshortname_long': [
        '<#^,portal_anyshortname#>'
    ],
    'portal_engineblurb': [
        '<#co_search#>',
        'powered by <#co_cool_technology#>',
    ],
    'portal_anyname': [
        '<#portal_autos#>',
        '<#portal_computers#>',
        '<#portal_entertainment#>',
        '<#portal_games#>',
        '<#portal_health#>',
        '<#portal_home#>',
        '<#portal_society#>',
        '<#portal_shopping#>',
        '<#portal_sports#>',
        '<#portal_business#>',
    ],
    'portal_name': [
        '<#company#> <#co_search#>',
    ],
    'portal_resultpagetitle': [
        '<#portal_resultpagetitle_default#><#co_media#>',
        '<#co_cool_technology#>',
        '<#co_newssource#>',
        '<#press#>',
        '<#jargon#>',
        '<#name#>',
        '<#broker#>',
    ],
    'portal_resultpagetitle_default': [
        '<#co_creative#>',
    ],
    'portal_searchbutton': [
        'Search',
        'Find',
        'Look for:',
        'Look up:',
        'Show me',
    ],
    'portal_searchhelp': [
        """The <#portal_name#> help pages enable you to get the most from your search experience. <#portal_name#> is one of the most powerful tools on the Internet, and we are dedicated to helping you use its features to their maximum potential.
                <P>The Quick Start guide below will help you get started searching in a matter of minutes. For more in-depth help, we have included pages explaining each area of <#portal_name#>. From Web search and Advanced Search to news, shopping, discussion and more, each help page explains all the available functions in detail.
                <P>If you cannot find what you are looking for in the help pages, try our list of Frequently Asked Questions. This list of common questions and answers is likely to contain the information you are looking for.
                <P>If you have a question that is not answered by any of our documentation, please feel free to contact us. We will do our best to get you the answers you need as quickly as possible.
                <P>Thank you for using <#portal_name#>, the most comprehensive Web index available. """,
    ],
    'portal_searchline': [
        'Search <#company#> archives',
        'Look it up with <#co_search#>',
        'Find it',
        'Check availability',
    ],
    'portal_subscribebutton': [
        'Join',
        'Sign me up',
    ],
    'portal_subscribeline': [
        '<#company#> <#paper_generic_English#>',
        'Keep informed',
        'Stay in touch',
        'Our Mailinglist',
        'Investors Mailinglist',
        'Factsheet',
        'Corporate News',
    ],
    'portal_autos': [
        'Autos',
        'Classic',
        'Dealers',
        'Manufacturers...',
        'Parts',
        'Hotrods',
        'Trucks',
        u'SUV’s',
        '6+ Wheels',
        'Formula1',
        'Wrecks',
        'Paintjobs',
        'Service',
        'Garage',
        'Mufflers',
        'Gasoline',
        '<#car_hot_rods#>',
        '<#car_hot_rods#>',
        '<#car_hot_rods#>',
        '<#car_brand#>',
    ],
    'portal_business': [
        'Business & Finance',
        'Industries',
        'Jobs',
        'Investing',
        'Employment',
        'Officespace',
        'Now Hiring',
        'Now Firing',
        'Suits',
        'Lawyers',
        'Legal Aid',
        u'One-minute IPO’s',
        'Hot Stocks',
        '<#^,j_thing#>',
    ],
    'portal_categories': [
        'entertainment',
        'art',
        'autos',
        'business',
        'computers',
        'games',
        'health',
        'home',
        'internet',
        'news',
        'reference',
        'regional',
        'science',
        'society',
        'sports',
    ],
    'portal_computers': [
        'Computers',
        'Software',
        'Hardware',
        'Graphics',
        'Controllers',
        'Printers',
        'Cables',
        'Repairs',
        'Service',
        'Shareware',
        'MP3',
        'FireWire',
        'Cameras',
        'Offers',
        'Deals',
    ],
    'portal_entertainment': [
        'Arts & Entertainment',
        'Movies',
        'TV',
        'Music',
        'Stars',
        'Quizshows',
        'Commercials',
        'Soaps',
    ],
    'portal_games': [
        'Games',
        'Video',
        'Role-Playing',
        'Gambling',
        'Simulation',
        'X-Box',
        'Casino',
        'Doom',
        'Quake',
        'Tetris',
        'Playstation',
    ],
    'portal_health': [
        'Health & Fitness',
        'Conditions',
        'Medicine',
        'Alternative',
        'Quaks',
        'Witchcraft',
        'Homeopathy',
        'Pains',
        'Aches',
        'Family Planning',
        'Accidents',
        'First Aid',
        'Hospitals',
        'Doctors',
        'Health Chat',
    ],
    'portal_home': [
        'Home & Family',
        'Kids',
        'Houses',
        'Consumers',
        'DIY',
        'Products',
        'Real Estate',
        'Homes',
        'Building',
        'Porches',
        'Barbecues',
        'Appliances',
        'Gardening',
        'Cooking',
    ],
    'portal_internet': [
        'Internet',
        'Chat',
        'Email',
        'WWW',
        'The Web',
        'The Net',
        'IRC',
        'Browsers',
        'Plugins',
        'Software',
        'Shareware',
        'Phone',
        'Stock',
    ],
    'portal_news': [
        'News & Media',
        'Online',
        'Magazines',
        'Newspapers',
        'Headlines',
        'The World',
        'Focus',
        'Old Media',
        'Newer Media',
        'Print',
        'Dead Media',
        '100 Years ago...',
    ],
    'portal_recreation': [
        'Recreation & Travel',
        'Food',
        'Outdoors',
        'Humor',
        'Adult',
        'Sports',
        'Gardening',
        'Driving',
        'Your Car',
        'Your Money',
        'Smoking',
    ],
    'portal_reference': [
        'Reference',
        'Maps',
        'Education',
        'Libraries',
        'Dictionaries',
        'Lists',
        'Encyclopedia',
        'Books',
        'Printed Matter',
    ],
    'portal_regional': [
        'Regional',
        'US',
        'Canada',
        'UK',
        'Europe',
        '<#countries_major#>',
        '<#city#>',
        'Areas',
        'Local Chains',
        'ChainFinder',
    ],
    'portal_science': [
        'Science',
        'Biology',
        'Psychology',
        'Physics',
        '<#^,sci_disciplines#>',
        '<#^,sci_pseudo#>',
    ],
    'portal_shopping': [
        'Shopping',
        'Auction',
        'Compare',
        'WWW Sites',
    ],
    'portal_society': [
        'Society & Culture',
        'People',
        'Religion',
        'Issues',
        'Stars',
        'Famous People',
        'Dead People',
        'Interesting People',
        'Lost People',
    ],
    'portal_sports': [
        'Sports',
        'Baseball',
        'Soccer',
        'Football',
        'Tennis',
        'Jogging',
        'Tetris',
        'Thumbwrestling',
        'Wrestling',
    ],
    'search_details': [
        u'While thousands flock to the web every hour, most, unfortunately, do little to differentiate their online <#j_noun_pl#>.',
        u'Your web design, graphic design, hosting, update, maintenance, consulting, one-stop solution',
        u'This work sheet assists you with the planning stage of your website. We hope it provides an opportunity to fine tune your thoughts and expectations of the website you are going to create.',
        u'It’s not easy aggregating content from a disparate group of independent sources, as anyone at <#co_search#> is likely to tell you. Charging for that content is even harder.',
        u'Generally speaking, you should consider a) your ISP’s (Internet Service Provider’s) setup charges and monthly fees for providing Internet access; b) your ISP’s setup charges and monthly fees for',
        u'Large files such as audio and video clips load in seconds instead of taking several minutes (as on a modem connection) ',
        u'Special Services few people offer... <#town_us#> Digital prides itself on being able to work with nearly any kind of digital file, regardless of platform.',
        u'When any new media comes along it is initially implemented by <#j_noun_gerund#> paradigms from the established media.',
        u'Training and marketing programs including interactive and online catalogs, computer-based training (CBT), web-based training (WBT) and video training, interactive cd-roms, and websites.',
        u'Related Web Sites If you’re interested in learning more about the technologies at the heart of <#company_consolidated#>’s product bundles',
        u'Your <#j_noun_gerund#> resource for the Internet',
        u'Project planning and assigned responsibilities Project Organization Project Design Data types and flow charts Project Development Visual infrastructure map and storyboard',
        u'How We Can Help You: More Design Questions  - Small business Web site design that makes sense, with special emphasis on consulting, marketing, custom Perl, and very personal service.',
        u'Interactive Multimedia (IM) Production Checklist. I use a production checklist when I am scoping and planning IM, because I have to manage over a dozen different projects concurrently!',
        u'We are devoted to extensive research on the <#j_noun_gerund#> industry. This site goes beyond simple definitions to the heart of what makes things tick.',
    ],
    'search_synopsis': [
        u'<#_aname=name#><#_aname#>’s Home Page Last updated <#time_months#> 1<#figs#>, 1999. All about <#_aname#>’s work Some links More info E-Mail <#_aname#> Family sites',
        u'Abstract for <#name#>’s thesis',
        u'Effect of using <#j_adjective#> <#j_noun_sing#> in <#j_noun_gerund#> solutions',
        u'Prepared for the postgraduate studies program at U<#state_abbr#>',
        u'Welcome to <#p_events_tech_px#><#p_events_tech_sx#>! This is the OFFICIAL web site of the conference, sponsored by <#company#>.',
        u'The Web Site of <#alphabet_caps#><#alphabet_caps#><#alphabet_caps#>99, held in <#city#>, <#time_months#> 23-25, 199<#figs#>. The conference was organized by The <#p_oldbiz_px#> Consortium, and UN<#alphabet_caps#><#alphabet_caps#> (<#city#>)',
        u'<#_acity=city#><#acity#> ISP guide. <#search_details#>',
        u'<#names_last_patrician#> <#names_last_patrician#> Website Development. <#search_details#>',
        u'<#company#> - <#search_details#>',
        u'The <#_atechnology=co_cool_technology#><#_atechnology#> eMail Discussion List Website is a collaborative effort of the members of the <#_atechnology#> eMail Discussion List. For information, e-mail "subscribe@majordomo.<#i_host_random#>"',
        u'<#_acompany=company#><#_acompany#> Job Openings - <#_acompany#> Networks Available Job Openings',
        u'<#names_first#>’s <#jargon#> FAQ - What’s involved? <#search_details#>',
        u'<#co_search#> allows you to bring materials to the attention of users who might not otherwise seek you out, or find you easily.',
        u'Links: <#names_last#>. <#search_details#>',
        u'Welcome to <#company_consolidated#>. <#corporate_prod_announcement_headline#>',
        u'<#company_consolidated#>. <#corporate_prod_announcement_headline#>',
        u'<#j_thing#>, <#j_thing#>, <#j_thing#>, <#j_thing#>',
        u'If you would like <#alphabet_caps#><#alphabet_caps#><#alphabet_caps#>’s web professionals to help you create a site, please fill in the information below. Name: Email Address: Phone Number: Company Name: Company Address:',
        u'<#company#> - About Us - Press Releases - 1999  - (PDF file, 23K) FOR IMMEDIATE RELEASE. <#city#>, <#time_months#> 15, 1998. When researching <#j_adjective#> or customized Web-based information technology training',
        u'<#i_host_gov#>-web-l archive: Content of Web Servers - <#alphabet_caps#><#alphabet_caps#><#alphabet_caps#>’s perspective  - Admin (<#eMail_gov#>) 2<#figs#> <#time_months#> 199<#figs#> 0<#figs#>:0<#figs#>:<#figs#><#figs#> +1200',
        u'<#i_host_edu#>-web-l archive: Changes to <#i_host_edu_departments#> department servers PLEASE READ. Our clients want to know about the department, and where the most appropriate place for information is.',
        u'<#p_whatever#>  - In an era of unprecedented information technology, <#company#>’s business is to assist organizations to rethink their business plans and implement a digital communications strategy.',
        u'<#time_months#> 1<#figs#>, 1999. <#search_details#>',
        u'<#co_creative#> New Offices: <#address#> <#search_details#>',
        u'<#co_creative#> - extensive research on the <#j_noun_gerund#> industry. <#search_details#>',
        u'<#name#>’s Tips Page  - This is the main one I use, a <#names_last_patrician#> <#alphabet_caps#><#alphabet_caps#> with <#alphabet_caps#><#alphabet_caps#>-<#figs#> attachment. When travelling, I always pack a <#names_last_patrician#> <#figs#>00 adapter, for 110/220V',
        u'<#co_cool_technology#>. <#address#> Driver Software and PDF Manual Downloads For all products Information about firmware upgrades for the <#alphabet_caps#><#alphabet_caps#>-<#figs#>00 Series',
        u'<#i_host_random#> index. This page has been superseded by new index, divided into three sections for easier downloading. This page will no longer be updated.',
        u'<#sci_elements#> Retail  - Retailer of over 4,000 at low discount prices! Shipping by FedEx for next day delivery AT NO COST within <#state_abbr#>.',
        u'The <#alphabet_caps#><#alphabet_caps#><#alphabet_caps#> staff’s account of <#news_disaster#>. Keywords: <#sci_elements#>, <#bank#>',
        u'Destination <#country#>! Travel rates | Tours | Packages | Links | Senior Citiz... <#URL#>',
        u'archive: Re: <#j_thing#>  - <#name#> (<#eMail#>) <#time_usenet#> > <#name#> wrote: > <#search_details#>',
        u'archive: Re: Re: <#j_thing#>  - <#name#> (<#eMail_biz_info#>) <#time_usenet#> > I have been trying to find out about a related topic, namely well def...',
        u'<#co_cool_technology#> Version 2.<#figs#>: Review by <#name#> (excerpted from <#newspapers#>, <#figs#>/<#figs#>/9<#figs#>)',
        u'<#_aname=name#><#_aname#> site - homepage  - Information about contemporary novelist <#_aname#>, with interviews with the author and excerpts from the new book.',
        u'My thanks to <#name#>, who sent me this information. If you can match any of this or know any of these people, please let me know! This page needs work, and I know there are people out there who can fill in all the blanks!',
        u'<#_aSurname=names_last#><#_aSurname#> Family  - First Generation <#names_first_patrician#> <#_aSurname#> was born in <#town_us#>, <#state_name#>, USA <#time_months#> 2<#figs#>, 18<#figs#><#figs#>. He married <#names_first_female#> <#names_last#>, who was born in in <#town_us#>, <#state_name#>, USA <#time_months#> 1<#figs#>...',
        u'<#p_business_px#>Shop Home Page  - The Biggest Store! Ever! 4<#figs#><#figs#>,000+ net sq. ft. of Exhibits 1,<#figs#>00+ Exhibits 1<#figs#>00+ First-time Exhibitors 4<#figs#>0+ Educational Seminars Exciting New Stores of the Future Centerpiece',
        u'<#alphabet_caps#><#alphabet_caps#>PAC - The <#names_last_patrician#> Center Political Action Committee. <#pol_US_guy#>, <#pol_US_guy#>, <#pol_US_guy#>, <#pol_US_guy#>...<#company_consolidated#> Archive: Re: <#news_headline#> - <#name#> (<#eMail_biz_info#>) <#time_usenet#> >This is a multi-part message in MIME format. ------=_NextPart_000_001B_01BDF<#figs_rand_5digit#>.F<#figs_rand_5digit#>B0 Content-Type: text/plain; charset="iso-8859-1" Content-Transfer-Encoding:quoted-printable',
        u'Re: <#newssource#> - <#name#> (<#eMail_biz_info#>) <#time_usenet#> >This is a multi-part message in MIME format. ------=_NextPart_000_001B_01BDF<#figs_rand_5digit#>.F<#figs_rand_5digit#>B0 Content-Type: text/plain; charset="iso-8859-1" Content-Transfer-Encoding:quoted-printable',
        u'<#i_host_edu#>-L archive: In a message dated <#time_usenet#>, <#name#> wrote: "<#search_details#>',
        u'<#names_first#>’s Web-Page - Sei mir gegrü√üt Fremder, der Du es wagtest Dich aus den unendlichen Weiten des Internet Dich hierher in meine bescheidene Web-Page zu begeben.',
        u'SEXY NAKED TEENS!!! HOLLAND’S BEST COLLECTION OF XXX GIRLS. DOWNLOAD FREE PICS IN NON-MEMBERS AREA. AVI’S. MPEG’S.',
        u'<#names_first_female#> Us and Stuff: "Related" Sites: Resumes for: Pages revised as sanity allows...most recently on <#figs#>/<#figs#>/99. Shameless self-absorption by Day Job: <#company#> Title this week: "<#jobs_bullshit#>".',
        u'<#name#>’s Homepage  - to my home page Course Links <#_dept=i_host_edu_departments#><#_dept#>2<#figs#><#figs#> <#_dept#>3<#figs#><#figs#> <#_dept#>4<#figs#><#figs#> Independent Studies Teaching Portfolio Philosophy Supplements Psychology Links Teaching Resources',
        u'<#name#>,REALTOR,Broker,Internet Real Estate Company,<#town_us#>,<#state_name#>,and all surrounding areas.Listings:<#URL#>',
        u'Re: addendum  - Subject: Re: addendum. From: <#name#> (<#eMail#>) ><#names_first#> asks that I repost... hehe, here it is.  :-)',
        u'<#newspapers#>: Breaking News: <#news_headline#>',
        u'<#newspapers#>. <#time_usenet#> <#news_headline#>',
        u'<#news_headline#> (<#newssource#>, posted <#time_usenet#>)',
        u'<#newssource#> News: <#time_usenet#> <#news_headline#>',
        u'<#name#>’s web site. <#address#>',
        u'<#BLURB_IPO#>',
        u'<#i_host_mil#> activities report, <#figs#>/98. Records of <#syllables#><#syllables#> division, Col. <#names_last_patrician#> commanding',
        u'<#company#> <#navigation#> | <#navigation#> | <#navigation#> | <#navigation#> | <#navigation#> | <#navigation#> | <#navigation#>...',
        u'<#eurobank#>. Introduction | <#navigation#> | <#navigation#> | <#navigation#> | <#navigation#> | <#navigation#> | <#navigation#>...',
        u'<#company#>',
        u'<#company#> Staff: <#staff_nameandrank#>',
        u'<#company#>: <#staff_nameandrank#>',
        u'<#staff_nameandrank#>, <#company#>. For information, write <#eMail_biz_info#>',
        u'<#name#>’s <#_idol=lit_figures#><#_idol#> web page. <#_idol#>’s work, <#_idol#> links, <#_idol#> events, <#_idol#> articles',
        u'Jobs at <#newssource#>. Needed: <#jobs_bullshit#>; <#jobs_bullshit#>; <#jobs_bullshit#>',
        u'<#company#> Human Resources. Now accepting applications for <#jobs_bullshit#> and <#jobs_bullshit#>',
        u'<#search_details#>',
        u'<#search_details#>',
        u'<#search_details#>',
        u'<#search_details#>',
        u'<#search_details#>',
        u'<#search_details#>',
    ],
    }

