# -*- coding: UTF-8 -*-
# -----------------------------------------------------------------------------
#
#     P A G E B O T
#
#     Copyright (c) 2016+ Buro Petr van Blokland + Claudia Mens & Font Bureau
#     www.pagebot.io
#     Licensed under MIT conditions
#     Made for usage in DrawBot, www.drawbot.com
# -----------------------------------------------------------------------------
#
#     cssbuilder.py
#
#     U N D E R  D E V E L O P M E N T
#
#     This builder is being worked on. 
#     It will generate the export .css from all CSS-based style values in the element tree,
#     which will be used by the HtmlBuilder to generate a close representation of the 
#     document as interactive & responsive website.
#
import codecs
import pagebot
from basebuilder import BaseBuilder
from pagebot.toolbox.transformer import color2Css

class CssBuilder(BaseBuilder):

    def build(self, e, view):
        u"""
        Builds the CSS for Element e and downwards, using the view parent document 
        as reference for styles.
        """
        assert self.path is not None
        line = '\t'+'.'*70+'\n'
        out = codecs.open(self.path, 'w', 'utf-8')
        out.write('@charset "UTF-8";\n')
        out.write("/*\n%s\tGenerated by PageBot Version %s\n%s*/\n" % (line, pagebot.__version__, line))

        doc = e.doc
        self.buildRootStyle(doc, out)
        self.buildMainStyles(doc, out)
        out.close()

    STYLE2CSS = {
        'fill': ('background-color: %s;', (1, 1, 1), color2Css),
        'font': ('font-family: %s;', 'Verdana, Sans', None),
        'fontSize': ('font-size: %spx;', 12, None),
        'textFill': ('color: %s;', (0, 0, 0), color2Css),
        'leading': ('line-height: %spx;', None, None),
        'rLeading': ('line-height: %sem;', '%0.2f'%1.3, None),
    }
    def _writeStyleValue(self, name, value, out):
        u"""Write the converted style value as CSS, using self.STYLE2CSS for conversion parameters."""
        if name in self.STYLE2CSS:
            cssName, default, f = self.STYLE2CSS[name]
            cssValue = value or default
            if f is not None:
                cssValue = f(cssValue)
            if cssValue is not None:
                out.write('\t'+(cssName % cssValue)+(' /* %s:%s */\n' % (name, `value`)))
                return True # Mark that we found it
        return False

    def _buildStyle(self, doc, out, style):
        u"""Export the style parameters as translated CSS values."""
        # For now write all values as comment as development reference.
        notProcessed = {}
        for parName, value in sorted(style.items()):
            if not self._writeStyleValue(parName, value, out):
                notProcessed[parName] = value

        # For now write all unprocessed values as comments a development reference.
        out.write('/*')
        for parName, value in sorted(notProcessed.items()):
    		out.write('\t%s: %s;\n' % (parName, value))
        out.write('*/\n')

    def buildRootStyle(self, doc, out):
    	u"""Translate the doc.rootStyle to the root body{...} CSS style using doc.rootStyle values."""
    	out.write('body {\n')
        self._buildStyle(doc, out, doc.styles['root'])
    	out.write('}\n\n')

    def buildMainStyles(self, doc, out):
    	u"""Build the styles for text elements, as defined in the doc.styles dictionary."""
    	for styleName, style in sorted(doc.styles.items()):
            if styleName == 'root':
                continue
            out.write('%s {\n' % styleName)
            self._buildStyle(doc, out, style)
            out.write('}\n\n')

    def buildElementStyles(self, doc, out, e=None):
        u"""Recursively build all style values into CSS."""
    	if e is None:
    		self.builfElementStyle(doc, out, self)
    	else:
            out.write('.%s {\n' % e.name, )
            self._buildStyle(doc, out, e.style)
            out.write('}\n\n')
            for child in e.getElements():
                self.buildElementStyles(doc, out, child)


