# -*- coding: UTF-8 -*-
# -----------------------------------------------------------------------------
#
#     P A G E B O T
#
#     Copyright (c) 2016+ Type Network, www.typenetwork.com, www.pagebot.io
#     Licensed under MIT conditions
#     Made for usage in DrawBot, www.drawbot.com
# -----------------------------------------------------------------------------
#
#     cssbuilder.py
#
import codecs
import pagebot
from basebuilder import BaseBuilder

class CssBuilder(BaseBuilder):

    def build(self, e, view):
        u"""
        Builds the CSS for Element e and downwards, using the view parent document 
        as reference for styles.
        """
        assert self.path is not None
        line = '\t'+'.'*70+'\n'
        out = codecs.open(self.path, 'w', 'utf-8')
        out.write('@charset "UTF-8";\n')
        out.write("/*\n%s\tGenerated by PageBot Version %s\n%s*/\n" % (line, pagebot.__version__, line))

        doc = e.doc
        self.buildRootStyle(doc, out)
        self.buildMainStyles(doc, out)
        out.close()

    def _buildStyle(self, doc, out, styleName, style):
		out.write('.%s {\n' % styleName)
		for parName, value in sorted(style.items()):
			out.write('\t%s: %s;\n' % (parName, value))
		out.write('}\n\n')

    def buildRootStyle(self, doc, out):
    	u"""Translate the doc.rootStyle to the root body{...} CSS style."""
    	out.write('body {\n')
    	out.write('/*')
    	for name, value in sorted(doc.styles['root'].items()):
    		out.write('\t%s: %s;\n' % (name, value))
    	out.write('*/\n')
    	out.write('}\n\n')

    def buildMainStyles(self, doc, out):
    	u"""BUild the styles for text elements, as defined in the doc.styles dictionary."""
    	for styleName, style in sorted(doc.styled.getItems()):
    		self._buildStyle(doc, out, styleName, style)

    def buildElementStyles(self, doc, out, e=None):
    	if e is None:
    		self.builfElementStyle(doc, out, self)
    	else:
    		self._buildStyle(doc, out, e.name, e.style)
    		for child in e.getElements():
    			self.buildElementStyles(doc, out, child)


