# -*- coding: UTF-8 -*-
#
#    blurb.py
#
import blurbwriter

class Blurb(object):
    """
    
    The ``Content`` is a wrapper around the filibuster ``BlurbWriter``
    of Erik van Blokland and Jonathan Hoefler. There is supposed to be only one instance of
    the writer installed in the system.
    """
    def __init__(self, content=None):
        import content
        #from filibuster import content
        self.writer = blurbwriter.BlurbWriter(content.content())
    
    def getBlurb(self, type, cnt=None):
        u"""
        
        The ``getBlurb`` method answers a random generated blurb of ``type``.
        The full list of available types get be obtained by calling ``self.getContentType()``.
        
        """
        if cnt is not None:
            return ' '.join(self.writer.write(type).split(' ')[:cnt])
        return self.writer.write(type)
   
    def getBlurbTypes(self):
        u"""
        
        The ``getBlurbTypes`` answers a list of names of all types of content blurbs
        that can can be generated by the writer.
        
        """
        return self.writer.keywords
    
if __name__ == '__main__':
    w = Blurb()
    for t in w.getBlurbTypes():
        print t, w.getBlurb(t)

    print w.getBlurb('filibuster_about')
    print w.getBlurb('aerospace_headline')
    print w.getBlurb('address')
    print
    for i in range(10):
        print w.getBlurb('politics_euro_headline')
    #print w.getBlurb('aerospace_headline', 3)
    #print w.getBlurbTypes()
