#!/bin/bash
set -ev
export PWD="Lib/pagebot"
python3 $PWD/contexts/basecontext/bezierpath.py
python3 $PWD/contexts/basecontext/basebeziersegment.py
python3 $PWD/contexts/basecontext/beziercontour.py
python3 $PWD/contexts/basecontext/basecontext.py
python3 $PWD/contexts/basecontext/basebeziercontour.py
python3 $PWD/contexts/basecontext/__init__.py
python3 $PWD/contexts/basecontext/baseimageobject.py
python3 $PWD/contexts/basecontext/basebuilder.py
python3 $PWD/contexts/basecontext/abstractcontext.py
python3 $PWD/contexts/basecontext/basebezierpoint.py
python3 $PWD/contexts/basecontext/babelstring.py
python3 $PWD/contexts/basecontext/basebezierpath.py
python3 $PWD/contexts/__init__.py
python3 $PWD/contexts/markup/sitebuilder.py
python3 $PWD/contexts/markup/svgbuilder.py
python3 $PWD/contexts/markup/__init__.py
python3 $PWD/contexts/markup/svgcontext.py
python3 $PWD/contexts/markup/xmlbuilder.py
python3 $PWD/contexts/markup/htmlcontext.py
python3 $PWD/contexts/markup/htmlbuilder.py
python3 $PWD/contexts/sketchcontext/sketchcontext.py
python3 $PWD/contexts/sketchcontext/sketchbuilder.py
python3 $PWD/contexts/sketchcontext/__init__.py
python3 $PWD/contexts/flatcontext/flatcontext.py
python3 $PWD/contexts/flatcontext/flatbuilder.py
python3 $PWD/contexts/flatcontext/__init__.py
python3 $PWD/contexts/flatcontext/flatbezierpath.py
python3 $PWD/style.py
python3 $PWD/contributions/markdown/__init__.py
python3 $PWD/contributions/markdown/literature.py
python3 $PWD/contributions/markdown/footnotes.py
python3 $PWD/contributions/markdown/inline.py
python3 $PWD/contributions/__init__.py
python3 $PWD/contributions/filibuster/titlecase.py
python3 $PWD/contributions/filibuster/__init__.py
python3 $PWD/contributions/filibuster/content/quotations.py
python3 $PWD/contributions/filibuster/content/superheroes.py
python3 $PWD/contributions/filibuster/content/filibuster.py
python3 $PWD/contributions/filibuster/content/event.py
python3 $PWD/contributions/filibuster/content/reviews.py
python3 $PWD/contributions/filibuster/content/boymechanic.py
python3 $PWD/contributions/filibuster/content/internet.py
python3 $PWD/contributions/filibuster/content/staff.py
python3 $PWD/contributions/filibuster/content/sports.py
python3 $PWD/contributions/filibuster/content/siliconvalley.py
python3 $PWD/contributions/filibuster/content/portal.py
python3 $PWD/contributions/filibuster/content/geography.py
python3 $PWD/contributions/filibuster/content/stylewars.py
python3 $PWD/contributions/filibuster/content/designarticle.py
python3 $PWD/contributions/filibuster/content/politics.py
python3 $PWD/contributions/filibuster/content/realestate.py
python3 $PWD/contributions/filibuster/content/sciences.py
python3 $PWD/contributions/filibuster/content/letterror.py
python3 $PWD/contributions/filibuster/content/filenames.py
python3 $PWD/contributions/filibuster/content/living.py
python3 $PWD/contributions/filibuster/content/aerospace.py
python3 $PWD/contributions/filibuster/content/corporate.py
python3 $PWD/contributions/filibuster/content/design.py
python3 $PWD/contributions/filibuster/content/__init__.py
python3 $PWD/contributions/filibuster/content/financial.py
python3 $PWD/contributions/filibuster/content/classified.py
python3 $PWD/contributions/filibuster/content/names.py
python3 $PWD/contributions/filibuster/content/music.py
python3 $PWD/contributions/filibuster/content/horoscope.py
python3 $PWD/contributions/filibuster/content/entertainment.py
python3 $PWD/contributions/filibuster/content/modernmedia.py
python3 $PWD/contributions/filibuster/content/book_reference.py
python3 $PWD/contributions/filibuster/content/twitter.py
python3 $PWD/contributions/filibuster/content/legalese.py
python3 $PWD/contributions/filibuster/content/articles.py
python3 $PWD/contributions/filibuster/content/navigation.py
python3 $PWD/contributions/filibuster/content/jargon.py
python3 $PWD/contributions/filibuster/content/auction.py
python3 $PWD/contributions/filibuster/content/literature.py
python3 $PWD/contributions/filibuster/content/commercial.py
python3 $PWD/contributions/filibuster/content/medical.py
python3 $PWD/contributions/filibuster/content/news.py
python3 $PWD/contributions/filibuster/content/creditcard.py
python3 $PWD/contributions/filibuster/content/journalism.py
python3 $PWD/contributions/filibuster/content/general.py
python3 $PWD/contributions/filibuster/content/automotive.py
python3 $PWD/contributions/filibuster/test.py
python3 $PWD/contributions/filibuster/example.py
python3 $PWD/contributions/filibuster/blurb.py
python3 $PWD/contributions/filibuster/blurbwriter.py
python3 $PWD/contributions/adobe/__init__.py
python3 $PWD/contributions/adobe/kerndump/getKerningPairsFromOTF.py
python3 $PWD/contributions/adobe/kerndump/__init__.py
python3 $PWD/contributions/adobe/kerndump/dumpKerningFeatureFromOTF.py
python3 $PWD/composer.py
python3 $PWD/gradient.py
python3 $PWD/publications/ads/__init__.py
python3 $PWD/publications/ads/basead.py
python3 $PWD/publications/calendars/basecalendar.py
python3 $PWD/publications/calendars/__init__.py
python3 $PWD/publications/calendars/photocalendar/monthpage.py
python3 $PWD/publications/calendars/photocalendar/coverpage.py
python3 $PWD/publications/calendars/photocalendar/__init__.py
python3 $PWD/publications/brochures/__init__.py
python3 $PWD/publications/brochures/basebrochure.py
python3 $PWD/publications/posters/baseposter.py
python3 $PWD/publications/posters/__init__.py
python3 $PWD/publications/magazines/__init__.py
python3 $PWD/publications/magazines/glossy/__init__.py
python3 $PWD/publications/magazines/glossy/parts.py
python3 $PWD/publications/magazines/basemagazine.py
python3 $PWD/publications/portfolios/paintings/__init__.py
python3 $PWD/publications/portfolios/paintings/portfolioClaudia.py
python3 $PWD/publications/portfolios/paintings/parts.py
python3 $PWD/publications/portfolios/__init__.py
python3 $PWD/publications/portfolios/baseportfolio.py
python3 $PWD/publications/__init__.py
python3 $PWD/publications/books/literature/toc.py
python3 $PWD/publications/books/literature/cover.py
python3 $PWD/publications/books/literature/index.py
python3 $PWD/publications/books/literature/__init__.py
python3 $PWD/publications/books/literature/section.py
python3 $PWD/publications/books/literature/main.py
python3 $PWD/publications/books/literature/title.py
python3 $PWD/publications/books/__init__.py
python3 $PWD/publications/books/photobook/coverpage.py
python3 $PWD/publications/books/photobook/__init__.py
python3 $PWD/publications/books/photobook/titlepage.py
python3 $PWD/publications/books/basebook.py
python3 $PWD/publications/newspapers/classic/newspaper.py
python3 $PWD/publications/newspapers/classic/__init__.py
python3 $PWD/publications/newspapers/classic/title.py
python3 $PWD/publications/newspapers/classic/article.py
python3 $PWD/publications/newspapers/__init__.py
python3 $PWD/publications/newspapers/basenewspaper.py
python3 $PWD/publications/typespecimens/proofing/__init__.py
python3 $PWD/publications/typespecimens/proofing/proof.py
python3 $PWD/publications/typespecimens/proofing/pagewide.py
python3 $PWD/publications/typespecimens/proofing/tx.py
python3 $PWD/publications/typespecimens/__init__.py
python3 $PWD/publications/typespecimens/specimens.py
python3 $PWD/publications/typespecimens/basetypespecimen.py
python3 $PWD/publications/typespecimens/simplespecimen.py
python3 $PWD/publications/typespecimens/typespecimen.py
python3 $PWD/publications/manuals/__init__.py
python3 $PWD/publications/manuals/basemanual.py
python3 $PWD/publications/catalogs/__init__.py
python3 $PWD/publications/catalogs/basecatalog.py
python3 $PWD/publications/publication.py
python3 $PWD/publications/identities/baseidentity.py
python3 $PWD/publications/identities/__init__.py
python3 $PWD/publications/websites/nanosite/css/nanostyle_css.py
python3 $PWD/publications/websites/nanosite/nanosite.py
python3 $PWD/publications/websites/__init__.py
python3 $PWD/publications/websites/d3graphs/d3graphsite_DEPR.py
python3 $PWD/publications/websites/basesite.py
python3 $PWD/resources/images/__init__.py
python3 $PWD/resources/testfonts/google/__init__.py
python3 $PWD/resources/testfonts/google/roboto/axes/__init__.py
python3 $PWD/resources/testfonts/google/roboto/__init__.py
python3 $PWD/resources/testfonts/__init__.py
python3 $PWD/resources/testfonts/djr/bungee/__init__.py
python3 $PWD/resources/testfonts/djr/__init__.py
python3 $PWD/resources/testfonts/fontbureau/__init__.py
python3 $PWD/resources/color/__init__.py
python3 $PWD/resources/__init__.py
python3 $PWD/resources/languages/__init__.py
python3 $PWD/resources/texts/__init__.py
python3 $PWD/resources/templates/__init__.py
python3 $PWD/constants.py
python3 $PWD/typesetter.py
python3 $PWD/mathematics/__init__.py
python3 $PWD/mathematics/transform3d.py
python3 $PWD/__init__.py
python3 $PWD/server/__init__.py
python3 $PWD/server/adserver.py
python3 $PWD/server/tornadoserver/__init__.py
python3 $PWD/server/tornadoserver/baseserver.py
python3 $PWD/fonttoolbox/analyzers/acontour.py
python3 $PWD/fonttoolbox/analyzers/asegment.py
python3 $PWD/fonttoolbox/analyzers/apoint.py
python3 $PWD/fonttoolbox/analyzers/__init__.py
python3 $PWD/fonttoolbox/analyzers/glyphanalyzer.py
python3 $PWD/fonttoolbox/analyzers/acomponent.py
python3 $PWD/fonttoolbox/analyzers/apointcontextlist.py
python3 $PWD/fonttoolbox/analyzers/stems.py
python3 $PWD/fonttoolbox/analyzers/apointcontext.py
python3 $PWD/fonttoolbox/analyzers/fontanalyzer.py
python3 $PWD/fonttoolbox/fontnames.py
python3 $PWD/fonttoolbox/__init__.py
python3 $PWD/fonttoolbox/objects/fontinfo.py
python3 $PWD/fonttoolbox/objects/glyph.py
python3 $PWD/fonttoolbox/objects/__init__.py
python3 $PWD/fonttoolbox/objects/prevarfamily.py
python3 $PWD/fonttoolbox/objects/font.py
python3 $PWD/fonttoolbox/objects/family.py
python3 $PWD/fonttoolbox/ttftools.py
python3 $PWD/fonttoolbox/unicodes/__init__.py
python3 $PWD/fonttoolbox/unicodes/unicoderangesdata.py
python3 $PWD/fonttoolbox/unicodes/unicoderanges.py
python3 $PWD/fonttoolbox/variablefontbuilder.py
python3 $PWD/fonttoolbox/fontpaths.py
python3 $PWD/fonttoolbox/designspace/__init__.py
python3 $PWD/fonttoolbox/designspace/dsmodel.py
python3 $PWD/fonttoolbox/variablefontaxes.py
python3 $PWD/fonttoolbox/otlTools.py
python3 $PWD/mining/wikipedia/wikicontent.py
python3 $PWD/mining/wikipedia/__init__.py
python3 $PWD/mining/__init__.py
python3 $PWD/mining/filibuster/__init__.py
python3 $PWD/mining/filibuster/samplecontent.py
python3 $PWD/elements/pbtable.py
python3 $PWD/elements/ui/_future/uibutton.py
python3 $PWD/elements/ui/_future/uicanvas.py
python3 $PWD/elements/ui/_future/uiwindow.py
python3 $PWD/elements/ui/_future/uigroup.py
python3 $PWD/elements/ui/__init__.py
python3 $PWD/elements/vf
python3 $PWD/elements/vf/specimen.py
python3 $PWD/elements/vf/animationframe.py
python3 $PWD/elements/vf/designspacegraph4.py
python3 $PWD/elements/vf/designspacegraph5.py
python3 $PWD/elements/vf/designspacegraphblackbows.py
python3 $PWD/elements/vf/__init__.py
python3 $PWD/elements/vf/designspacegraph1.py
python3 $PWD/elements/vf/bezieranimation.py
python3 $PWD/elements/vf/designspacegraph6.py
python3 $PWD/elements/vf/designspacegrapharrows.py
python3 $PWD/elements/vf/designspacegraph2.py
python3 $PWD/elements/vf/designspacegraph3.py
python3 $PWD/elements/vf/designspacegraphworking.py
python3 $PWD/elements/vf/designspacegraph.py
python3 $PWD/elements/pbplacer.py
python3 $PWD/elements/pbdocwrap.py
python3 $PWD/elements/pbline.py
python3 $PWD/elements/pbpage.py
python3 $PWD/elements/pbimage.py
python3 $PWD/elements/pbrect.py
python3 $PWD/elements/web/ui/slide.py
python3 $PWD/elements/web/ui/__init__.py
python3 $PWD/elements/web/nanosite/__init__.py
python3 $PWD/elements/web/nanosite/siteelements.py
python3 $PWD/elements/web/__init__.py
python3 $PWD/elements/web/simplesite/__init__.py
python3 $PWD/elements/web/simplesite/siteelements.py
python3 $PWD/elements/web/barebonesslider/__init__.py
python3 $PWD/elements/web/barebonesslider/siteelements.py
python3 $PWD/elements/pbpolygon.py
python3 $PWD/elements/variablefonts/glyphdimensions.py
python3 $PWD/elements/variablefonts/stacked.py
python3 $PWD/elements/variablefonts/paragraphs.py
python3 $PWD/elements/variablefonts/animationframe.py
python3 $PWD/elements/variablefonts/basefontshow.py
python3 $PWD/elements/variablefonts/bio.py
python3 $PWD/elements/variablefonts/variablecircle.py
python3 $PWD/elements/variablefonts/__init__.py
python3 $PWD/elements/variablefonts/fittowidth.py
python3 $PWD/elements/variablefonts/variablescatter.py
python3 $PWD/elements/variablefonts/widths.py
python3 $PWD/elements/variablefonts/variablecube2.py
python3 $PWD/elements/variablefonts/variablecube.py
python3 $PWD/elements/variablefonts/waterfall.py
python3 $PWD/elements/variablefonts/cube.py
python3 $PWD/elements/variablefonts/variableglyphs.py
python3 $PWD/elements/variablefonts/glyphset.py
python3 $PWD/elements/variablefonts/fonticon.py
python3 $PWD/elements/variablefonts/sampler.py
python3 $PWD/elements/variablefonts/typeramps.py
python3 $PWD/elements/variablefonts/title.py
python3 $PWD/elements/pboval.py
python3 $PWD/elements/paths/__init__.py
python3 $PWD/elements/paths/glyphpath.py
python3 $PWD/elements/paths/pbpaths.py
python3 $PWD/elements/__init__.py
python3 $PWD/elements/pbgroup.py
python3 $PWD/elements/element.py
python3 $PWD/elements/newspapers/__init__.py
python3 $PWD/elements/newspapers/articles.py
python3 $PWD/elements/newspapers/headers.py
python3 $PWD/elements/pbimage2.py
python3 $PWD/elements/pbruler.py
python3 $PWD/elements/pbcodeblock.py
python3 $PWD/elements/dating/calendarmonth.py
python3 $PWD/elements/dating/__init__.py
python3 $PWD/elements/pbgalley.py
python3 $PWD/elements/views/htmlview.py
python3 $PWD/elements/views/googlecloudview.py
python3 $PWD/elements/views/pagemapview.py
python3 $PWD/elements/views/googleappsview.py
python3 $PWD/elements/views/__init__.py
python3 $PWD/elements/views/siteview.py
python3 $PWD/elements/views/mampview.py
python3 $PWD/elements/views/pageview.py
python3 $PWD/elements/views/gitview.py
python3 $PWD/elements/views/baseview.py
python3 $PWD/elements/pbtext.py
python3 $PWD/elements/pbartboard.py
python3 $PWD/elements/pbquire.py
python3 $PWD/toolbox/finder.py
python3 $PWD/toolbox/dating.py
python3 $PWD/toolbox/color.py
python3 $PWD/toolbox/units.py
python3 $PWD/toolbox/hyphenation.py
python3 $PWD/toolbox/drawing.py
python3 $PWD/toolbox/__init__.py
python3 $PWD/toolbox/timemark.py
python3 $PWD/toolbox/columncalc.py
python3 $PWD/toolbox/transformer.py
python3 $PWD/toolbox/markers.py
python3 $PWD/toolbox/loremipsum.py
python3 $PWD/document.py
python3 $PWD/conditions/floating.py
python3 $PWD/conditions/align.py
python3 $PWD/conditions/__init__.py
python3 $PWD/conditions/flow.py
python3 $PWD/conditions/columns.py
python3 $PWD/conditions/condition.py
python3 $PWD/conditions/text.py
python3 $PWD/conditions/score.py
python3 $PWD/templates/stackedtypography.py
python3 $PWD/templates/__init__.py
python3 $PWD/errors.py
python3 $PWD/readers/rereader.py
python3 $PWD/readers/__init__.py
python3 $PWD/readers/mdreader.py
python3 $PWD/readers/xmlreader.py
python3 $PWD/themes/backtothecity.py
python3 $PWD/themes/businessasusual.py
python3 $PWD/themes/wordlywise.py
python3 $PWD/themes/seasoningthedish.py
python3 $PWD/themes/__init__.py
python3 $PWD/themes/somethingintheair.py
python3 $PWD/themes/freshandshiny.py
python3 $PWD/themes/happyholidays.py
python3 $PWD/themes/basetheme.py
python3 $PWD/themes/fairytales.py
python3 $PWD/themes/intothewoods.py
python3 $PWD/stylelib.py
python3 $PWD/filepaths.py
python3 $PWD/article.py
