name: PageBot Test Bench

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  # https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners
  test-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - name: Check python
      run: |
        python3 --version
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Virtual Environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
        python -c "import sys; print('\n'.join(sys.path))"
    - name: Install
      run: |
        source venv/bin/activate
        pip3 install -r ./requirements.txt
        pip3 install -r ./test-requirements.txt
    - name: Run tests
      run: |
        mkdir _export
        pip3 search pagebot
        source venv/bin/activate
        ./scripts/pylint.sh
        ./scripts/tests-linux.sh
        coverage run -m pytest
    - name: Codecov Upload
      uses: codecov/codecov-action@v1
